server.host: "0.0.0.0"

elasticsearch.hosts: ["https://localhost:9200"]
elasticsearch.ssl.certificateAuthorities: ["/etc/kibana/certs/ca.crt"]
elasticsearch.ssl.verificationMode: certificate

xpack.security.encryptionKey: "${KBN_SECURITY_KEY}"
xpack.encryptedSavedObjects.encryptionKey: "${KBN_SAVEDOBJ_KEY}"
xpack.reporting.encryptionKey: "${KBN_REPORTING_KEY}"