metricbeat.modules:
  - module: system
    metricsets: ["cpu", "memory", "network", "diskio", "filesystem"]
    enabled: true
    period: 10s

output.logstash:
  hosts: ["10.34.66.18:5046"]
  ssl.enabled: false